# Generated by Django 5.1.2 on 2024-12-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviereview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
