# Generated by Django 5.1.2 on 2024-12-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movielike_remove_movie_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
