# Generated by Django 5.1.2 on 2024-12-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_vote_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
