# Generated by Django 5.1.2 on 2024-12-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_moviereview_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieLike',
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
